# Generated by Django 3.2 on 2021-05-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmood',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Angry', 'Angry'), ('Surprised', 'Surprised'), ('Neutral', 'Neutral')], max_length=50),
        ),
    ]
