# Generated by Django 3.2 on 2021-05-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_addr',
            field=models.GenericIPAddressField(default=None),
            preserve_default=False,
        ),
    ]
