# Generated by Django 3.2 on 2021-05-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_ip_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Angry', 'Angry'), ('Surprised', 'Surprised'), ('Neutral', 'Neutral')], max_length=150),
        ),
    ]
